#Bio-Data using input function
print('\t\"BIO_DATA"')
bd= input('Enter Your Birth Date : ')
rn= input('Enter Your Roll No. : ')
sec= input('Enter Section: ')
matric_grade=input('Enter Matric Grade : ')
matric_percentage=input('Enter Matric Percentage : ')
inter_grade=input('Enter Inter Grade : ')
inter_percentage=input('Enter Intermediate Percentage : ')
print('\n\t\"BIO-DATA\"')
print('\nBirth Date : ',bd)
print('\nRoll No. : ',rn)
print('\nSection : ',sec)
print('\nMatric Grade : ',matric_grade)
print('\nMatric Percentage : ',matric_percentage)
print('\nInter Grade : ',inter_grade)
print('\nInter percentage : ',inter_percentage)